radareorg/r2ai

- r2ai/code_block.py
- r2ai/interpreter.py
- r2ai/message_block.py
- r2ai/utils.py
> Fix live code/message blocks and simplify the code

- r2ai/auto.py
- r2ai/functionary/openai_types.py
- r2ai/functionary/prompt_template/__init__.py
- r2ai/functionary/prompt_template/base_template.py
- r2ai/functionary/prompt_template/prompt_template_v1.py
- r2ai/functionary/prompt_template/prompt_template_v2.py
- r2ai/functionary/schema.py
- r2ai/models.py
- r2ai/repl.py
This might work decently when we do the RAG or even just some more prompting, but it's nowhere near openai in terms of understanding. It does run functions now, but it's not very good at the r2 commands.
`llama-cpp-python` allegedly supports it, but I couldn't get it to work properly, so I pulled in the files I needed from the official functionary repo.
> Support functionary models for auto mode

- r2plugin/Makefile
Add system install/uninstall targets to r2plugin Makefile.
> Add r2plugin Makefile system install

- r2ai/backend/openapi.py
- r2ai/interpreter.py
> Use the requests library for openai/openapi only when necesary

- r2ai/interpreter.py
> Add llm.repeat_penalty option

- r2ai/interpreter.py
- r2ai/web.py
> Make sure we close the server properly when handling KeyboardInterrupt

- r2ai/web.py
> Only log shutting down webserver when running in ^C

- r2ai/web.py
> Dont loose the prompt when failing to start the webserver

- r2ai/ui/app.py
- r2ai/ui/app.tcss
**Checklist**
Fixes file browser bugs
> Fix TUI File Browser and chat bug

- r2ai/ui/app.py
- r2ai/ui/app.tcss
**Checklist**
Chat message formatting fixes
> Fix TUI Chat messages formatting

- r2ai/ui/app.py
- r2ai/ui/chat.py
**Checklist**
Formatting tool call text
> Fix TUI tool calls formatting

- main.py
- r2ai/auto.py
- r2ai/index.py
- r2ai/interpreter.py
- r2ai/main.py
- r2ai/pipe.py
- r2ai/repl.py
- r2ai/tab.py
> Make more stuff optional to load it as an r2 plugin again

- r2ai/ui/app.py
- r2ai/ui/chat.py
**Checklist**
ctrl+o to open binary, ctrl+m for model selector, error handling, some formatting updates
> TUI updates and some error handling

- r2ai/ui/app.py
**Checklist**
pops up input to put in the env
> TUI: Ask for API KEY if one is not set in env

- main.py
- r2ai/pipe.py
- r2ai/ui/app.py
- r2ai/ui/app.tcss
- r2ai/ui/chat.py
- r2ai/ui/r2cmd.py
> TUI: switch to using r2cmd {; get filename if binary already opened

- r2ai/env.py
- r2ai/interpreter.py
- r2ai/repl.py
> Support setting callbacks on env change; Move debug level set in env

- r2ai/pipe.py
**Checklist**
Fixing things to make sure whatever loaded binary is the same
> Make sure r2lang and r2 are in sync

- Makefile
- r2ai/plugin.py
**Checklist**
venv should be `source venv/bin/activate`. I also added stuff to clean, which is probably what caused your error.
> Makefile fixes

- MANIFEST.in
- pyproject.toml
> Add .tcss files to package

- decai/decai.r2.js
- r2ai/models.py
> Update claude sonnet version

- Makefile
**Checklist**
Replaced the non-portable calls to `source` in the Makefile with `.`.
> Use portable script sourcing

- r2ai/auto.py
- r2ai/completion.py
- r2ai/interpreter.py
- r2ai/large.py
- r2ai/models.py
- r2ai/partial_json_parser.py
**Checklist**
Sorry, big, but mostly template stuff.
> Rawdog auto

- r2ai/auto.py
> Auto updates to handle more params and non-streaming mode

- r2ai/ui/app.py
- r2ai/ui/chat.py
- r2ai/ui/model_select.py
> Fix VV for local models

- r2ai/interpreter.py
- r2ai/models.py
- r2ai/pipe.py
> Use lazy imports to speed up initial loading time

- r2ai/interpreter.py
> Fix for new models not yet added to litellm

- README.md
**Checklist**
This is just an attempt to make the `README.md` both more useful and more up-to-date, because several commands and infos in the documentation were no longer true or working.
The code is not changed.
> README documentation improvement to fix #102

- .github/workflows/ci.yml
- src/Makefile
- src/anthropic.c
- src/gemini.c
- src/openai.c
- src/openapi.c
- src/r2ai.c
- src/r2ai.h
> Update CI stuff and also build the C plugin

- pyproject.toml
- r2ai/auto.py
- r2ai/interpreter.py
> Python: auto fixes; better cost display

- decai/decai.r2.js
**Checklist**
1. A prompt reset option was implemented, but not advertised in usage(). I added it.
2. I noticed `-D` wasn't working... the issue was simply that `usage()` was wrong and that it was meant to be `-dD`. Fixed that.
> Updating usage with -R and -dD

- decai/decai.r2.js
**Checklist**
In some cases, decai is sending to the AI too long data file, and because of AI max input tokens limit, the AI refuses to respond. There are several solutions to this, such as getting a higher max input token limit from AI end, but that's not always feasible or with costs. Rather, I find that sending *truncated* data file *is an acceptable solution* in some cases. Yes, you won't get the entire function correctly decompiled as you only sent part of the `pdc` output, but still, sometimes you are only concerned by the beginning of the function + in several cases the AI extrapolates not too bad the rest ;-)
So, my solution is to tell decai that it may only send up to `maxInputTokens`. If my file is bigger, it will be truncated to the limit I set. 
Note that, by …
> Implementing max input tokens to be sent to AI as optional setting

- r2ai/auto.py
> Fix for o3-mini

- r2ai/interpreter.py
- r2ai/repl.py
> Fix #122 and #124

- decai/decai.r2.js
**Checklist**
As suggested in the issue, the solution is to detect the markdown formatting for JSON and remove that. If we detect markdown on the first and last line, we'll remove the lines.
So, if the AI adequately returns pure JSON, this will work.
If the AI returns markdown triple quote, this works too.
> Decai auto

- src/Makefile
- src/anthropic.c
- src/auto.c
- src/gemini.c
- src/messages.c
- src/ollama.c
- src/openai.c
- src/openapi.c
- src/r2ai.c
- src/r2ai.h
- src/tools.c
- src/xai.c
**Checklist**
I know you dont like big PRs, but I don't see how this would be possible with small ones :)
I've got auto mode working for both anthropic and openai.
The idea here is to standardize everything on the OpenAI structure, and just handle Anthropic messages and responses by converting them. Everything else already has OpenAI-compatible providers.
> [WIP] Auto mode, rewrite everything (r2ai.c)

- src/anthropic.c
- src/auto.c
- src/messages.c
- src/openai.c
- src/r2ai.c
- src/r2ai.h
> Implement chat log; Add tokens to stats

- src/Makefile
- src/anthropic.c
- src/auto.c
- src/openai.c
- src/r2ai.c
- src/r2ai.h
- src/r2ai_http.c
- src/tools.c
> Use libcurl if available

- src/Makefile
- src/anthropic.c
- src/auto.c
- src/markdown.c
- src/markdown.h
- src/openai.c
- src/r2ai.c
- src/r2ai.h
- src/r2ai_http.c
- src/tools.c
> Use R2_CURL; Add javascript tool; Add Markdown renderer

- src/r2ai.c
- src/r2ai_http.c
- src/tools.c
> Add http retry with expo backoff

- src/auto.c
- src/openai.c
- src/tools.c
> Add ask_to_execute support; Add mistral and grok as providers

- src/anthropic.c
- src/auto.c
- src/messages.c
- src/r2ai.c
- src/r2ai.h
- src/tools.c
> Add support for anthropic thinking

- README.md
- decai/decai.r2.js
- r2ai/main.py
- r2ai/repl.py
- r2ai/tools.py
- src/r2ai.c
> Remove adding additional empty user message

- src/auto.c
- src/messages.c
- src/openai.c
- src/r2ai.h
> Add support for reasoning_content

- r2ai/auto.py
- r2ai/interpreter.py
retrieve base model name if finetuned model used
> clean model name

- src/Makefile
> Add system install for r2ai-plugin

- src/openai.c
- src/r2ai.c
- src/r2ai.h
- src/r2ai_http.c
> Add -e model=? to list models

- dist/docker/Dockerfile
Adding a docker-file that prepare all the r2ai/decai setup automaticlaly.
> Dockerfile for r2 + r2ai + decai + r2ghidra + nice .radare2rc

- decai/decai.r2.js
**Checklist**
Refactored decai.r2.js (untested) to be more customisable (used Claude by Anthropic).
We need to carry out some testing.
> Refactored decai.r2.js 

- README.md
**Checklist**
As requested, this is just an update on links to presentations and videos that concern r2ai.
> more references

- .github/workflows/ci.yml
> Include the r2ai plugin in the meson ci builds
